name: Reuse other workflow

on:
  workflow_dispatch:
       
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Call reusable workflow
      uses: ./.github/workflows/reusable.yml
      with:
        who-to-greet: '@Izhar' 

  use-output:
   runs-on: ubuntu-latest
   needs: call-workflow
   steps:
    - name: Output time set in the container
      run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"